# Generated by Django 3.0.5 on 2020-04-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='text',
            new_name='name',
        ),
    ]
