# Generated by Django 3.0.5 on 2020-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0002_auto_20200407_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('harnessID', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
