# Generated by Django 3.0.5 on 2020-04-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0003_auto_20200408_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ff_app.Owner'),
            preserve_default=False,
        ),
    ]
