# Generated by Django 3.0.5 on 2020-04-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0004_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='harnessID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
