# Generated by Django 3.0.5 on 2020-04-08 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0008_auto_20200408_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='harnessID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ff_app.Owner'),
        ),
    ]
