# Generated by Django 3.0.5 on 2020-04-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0010_auto_20200408_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('harnessID', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='harnessID',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='harness',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_app.Pet'),
        ),
    ]
