# Generated by Django 2.2.6 on 2020-04-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0012_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='disabilities',
            field=models.CharField(choices=[('blind', 'BLIND'), ('deaf', 'DEAF'), ('blind and deaf', 'BLIND AND DEAF'), ('none', 'NONE')], default='NONE', max_length=20),
        ),
    ]
