# Generated by Django 2.2.6 on 2020-04-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0013_pet_disabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='disabilities',
            field=models.CharField(choices=[('blind', 'blind'), ('deaf', 'deaf'), ('blind and deaf', 'blind and deaf'), ('none', 'none')], default='none', max_length=20),
        ),
    ]
