# Generated by Django 2.2.6 on 2020-05-05 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff_app', '0014_auto_20200427_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
                ('harness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff_app.Harness')),
            ],
        ),
    ]
